import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

interface AIContextValue {
  aiOffline: boolean
  setAiOffline: (v: boolean) => void
  language: string
  setLanguage: (lang: string) => void
}

const AIContext = createContext<AIContextValue>({
  aiOffline: false,
  setAiOffline: () => {},
  language: 'en',
  setLanguage: () => {},
})

export const translations: Record<string, Record<string, string>> = {
  en: {
    wayfinding: 'Wayfinding',
    accessibility: 'Accessibility',
    transport: 'Transport',
    title_wayfinding: 'Wayfinding & Routing',
    origin: 'Origin Gate',
    destination: 'Destination Section',
    routing_mode: 'Routing Mode',
    standard: 'Standard',
    accessible: 'Accessible',
    accessible_route: 'Accessible route',
    congestion: 'Use live congestion weights',
    find_route: 'Find Route',
    computing: 'Computing route…',
    route_found: 'Route Found',
    walking_directions: 'Walking Directions',
    path: 'Path',
    title_accessibility: 'Accessibility Wayfinding',
    assistance_profile: 'Assistance Profile',
    select_all: 'Select all that apply:',
    wheelchair: 'Wheelchair user',
    step_free: 'Step-free route required',
    service_animal: 'Service animal relief stop',
    sensory: 'Sensory-friendly routing',
    amenities: 'Accessible Amenities Nearby',
    step_free_route: 'Step-Free Accessible Route',
    distance: 'Distance',
    walk_time: 'Walk time',
    title_transport: 'Sustainable Transport',
    transport_subtitle: 'Find the greenest way to the stadium.',
    select_transport: 'Select Mode of Transport',
    calc_carbon: 'Calculate Carbon Emissions',
    travel_time: 'Estimated Travel Time',
    carbon_footprint: 'Carbon Footprint',
    est_cost: 'Estimated Cost',
    sustainable_option: 'Sustainable Option',
    simulate_ai: 'Simulate AI Offline',
    offline: 'OFFLINE',
    footer_text: 'GenAI never computes routes or distances — deterministic engine only',
    meta_desc_wayfinding: 'FanFlow AI — Fast and reliable stadium routing and wayfinding for FIFA World Cup 2026. Get deterministic directions with AI-phrased context.',
    meta_desc_accessibility: 'FanFlow AI — Accessible, step-free navigation, assistance profiles, and accessible amenities finder for World Cup stadium visitors.',
    meta_desc_transport: 'FanFlow AI — Compare carbon emissions, costs, and ETAs for sustainable transit, rideshare, and parking to get to the stadium.',
  },
  es: {
    wayfinding: 'Navegación',
    accessibility: 'Accesibilidad',
    transport: 'Transporte',
    title_wayfinding: 'Navegación y Rutas',
    origin: 'Puerta de Origen',
    destination: 'Sección de Destino',
    routing_mode: 'Modo de Ruta',
    standard: 'Estándar',
    accessible: 'Accesible',
    accessible_route: 'Ruta accesible',
    congestion: 'Usar pesos de congestión en vivo',
    find_route: 'Buscar Ruta',
    computing: 'Calculando ruta…',
    route_found: 'Ruta Encontrada',
    walking_directions: 'Direcciones para Caminar',
    path: 'Ruta',
    title_accessibility: 'Accesibilidad de Navegación',
    assistance_profile: 'Perfil de Asistencia',
    select_all: 'Seleccione todo lo que corresponda:',
    wheelchair: 'Usuario de silla de ruedas',
    step_free: 'Ruta sin escalones requerida',
    service_animal: 'Parada de alivio para animales de servicio',
    sensory: 'Ruta amigável para los sentidos',
    amenities: 'Servicios Accesibles Cercanos',
    step_free_route: 'Ruta Accesible Sin Escalones',
    distance: 'Distancia',
    walk_time: 'Tiempo de caminata',
    title_transport: 'Transporte Sostenible',
    transport_subtitle: 'Encuentra la forma más ecológica de llegar al estadio.',
    select_transport: 'Seleccionar Modo de Transporte',
    calc_carbon: 'Calcular Emisiones de Carbono',
    travel_time: 'Tiempo Estimado de Viaje',
    carbon_footprint: 'Huella de Carbono',
    est_cost: 'Costo Estimado',
    sustainable_option: 'Opción Sostenible',
    simulate_ai: 'Simular IA Fuera de Línea',
    offline: 'DESCONECTADO',
    footer_text: 'La IA nunca calcula rutas o distancias — solo motor determinista',
    meta_desc_wayfinding: 'FanFlow AI — Rutas rápidas y confiables en el estadio para la Copa Mundial de la FIFA 2026. Obtenga direcciones deterministas con contexto redactado por IA.',
    meta_desc_accessibility: 'FanFlow AI — Navegación accesible y sin escalones, perfiles de asistencia y buscador de servicios accesibles para los visitantes del estadio de la Copa Mundial.',
    meta_desc_transport: 'FanFlow AI — Compare emisiones de carbono, costos y ETA de transporte sostenible, viaje compartido y estacionamiento para llegar al estadio.',
  },
  fr: {
    wayfinding: 'Guidage',
    accessibility: 'Accessibilité',
    transport: 'Transport',
    title_wayfinding: 'Guidage et Itinéraires',
    origin: 'Porte d\'Origine',
    destination: 'Section de Destination',
    routing_mode: 'Mode d\'Itinéraire',
    standard: 'Standard',
    accessible: 'Accessible',
    accessible_route: 'Itinéraire accessible',
    congestion: 'Utiliser les poids de congestion en direct',
    find_route: 'Trouver l\'Itinéraire',
    computing: 'Calcul de l\'itinéraire…',
    route_found: 'Itinéraire Trouvé',
    walking_directions: 'Directions de Marche',
    path: 'Chemin',
    title_accessibility: 'Guidage d\'Accessibilité',
    assistance_profile: 'Profil d\'Assistance',
    select_all: 'Sélectionnez tout ce qui s\'applique :',
    wheelchair: 'Fauteuil roulant',
    step_free: 'Itinéraire sans marches requis',
    service_animal: 'Arrêt pour animaux d\'assistance',
    sensory: 'Itinéraire sensoriel',
    amenities: 'Équipements Accessibles à Proximité',
    step_free_route: 'Itinéraire Accessible Sans Marches',
    distance: 'Distance',
    walk_time: 'Temps de marche',
    title_transport: 'Transport Durable',
    transport_subtitle: 'Trouvez le moyen le plus vert de vous rendre au stade.',
    select_transport: 'Sélectionner le Mode de Transport',
    calc_carbon: 'Calculer les Émissions de Carbone',
    travel_time: 'Temps de Trajet Estimé',
    carbon_footprint: 'Empreinte Carbone',
    est_cost: 'Coût Estimé',
    sustainable_option: 'Option Durable',
    simulate_ai: 'Simuler l\'IA Hors Ligne',
    offline: 'HORS LIGNE',
    footer_text: 'L\'IA ne calcule jamais les itinéraires ou les distances — moteur déterministe uniquement',
    meta_desc_wayfinding: 'FanFlow AI — Guidage rapide et fiable dans le stade pour la Coupe du Monde de la FIFA 2026. Obtenez des itinéraires déterministes avec contexte formulé par l\'IA.',
    meta_desc_accessibility: 'FanFlow AI — Navigation accessible et sans marches, profils d\'assistance et recherche d\'équipements accessibles pour les visiteurs du stade de la Coupe du Monde.',
    meta_desc_transport: 'FanFlow AI — Comparez les émissions de carbone, les coûts et les ETA pour les transports en commun durables, le covoiturage et le parking pour aller au stade.',
  },
  ar: {
    wayfinding: 'التوجيه',
    accessibility: 'إمكانية الوصول',
    transport: 'النقل',
    title_wayfinding: 'التوجيه وتحديد المسار',
    origin: 'بوابة الانطلاق',
    destination: 'قسم الوجهة',
    routing_mode: 'طريقة التوجيه',
    standard: 'قياسي',
    accessible: 'سهل الوصول',
    accessible_route: 'مسار سهل الوصول',
    congestion: 'استخدام أوزان الازدحام المباشرة',
    find_route: 'البحث عن مسار',
    computing: 'جاري حساب المسار…',
    route_found: 'تم العثور على المسار',
    walking_directions: 'اتجاهات السير',
    path: 'المسار',
    title_accessibility: 'توجيهات سهولة الوصول',
    assistance_profile: 'ملف المساعدة',
    select_all: 'حدد كل ما ينطبق:',
    wheelchair: 'مستخدم كرسي متحرك',
    step_free: 'مطلوب مسار خالٍ من الدرج',
    service_animal: 'مكان راحة حيوانات الخدمة',
    sensory: 'مسار مناسب للحساسية الحسية',
    amenities: 'مرافق سهلة الوصول قريبة',
    step_free_route: 'مسار سهل الوصول بدون درج',
    distance: 'المسافة',
    walk_time: 'وقت السير',
    title_transport: 'النقل المستدام',
    transport_subtitle: 'البحث عن الطريق الأكثر خضرة إلى الملعب.',
    select_transport: 'اختر وسيلة النقل',
    calc_carbon: 'حساب انبعاثات الكربون',
    travel_time: 'وقت السفر المتوقع',
    carbon_footprint: 'البصمة الكربونية',
    est_cost: 'التكلفة المتوقعة',
    sustainable_option: 'خيار مستدام',
    simulate_ai: 'محاكاة غياب الذkاء الاصطناعي',
    offline: 'غير متصل',
    footer_text: 'لا يقوم الذكاء الاصطناعي مطلقًا بحساب المسارات أو المسafات - المحرك الحتمي فقط',
    meta_desc_wayfinding: 'FanFlow AI - توجيه وتحديد مسار سريع وموثوق في الملعب لكأس العالم لكرة القدم 2026. احصل على اتجاهات حتمية مع سياق مصاغ بواسطة الذكاء الاصطناعي.',
    meta_desc_accessibility: 'FanFlow AI - ملاحة سهلة الوصول وخالية من الدرج، وملفات مساعدة، وباحث عن المرافق الميسرة لزوار ملعب كأس العالم.',
    meta_desc_transport: 'FanFlow AI - قارن بين انبعاثات الكربون والتكاليف والأوقات المتوقعة للوصول لوسائل النقل المستدام، ومشاركة الركوب، ومواقف السيارات للوصول إلى الملعب.',
  },
  pt: {
    wayfinding: 'Navegação',
    accessibility: 'Acessibilidade',
    transport: 'Transporte',
    title_wayfinding: 'Navegação e Rotas',
    origin: 'Portão de Origem',
    destination: 'Seção de Destino',
    routing_mode: 'Modo de Rota',
    standard: 'Padrão',
    accessible: 'Acessível',
    accessible_route: 'Rota acessível',
    congestion: 'Usar pesos de congestionamento ao vivo',
    find_route: 'Buscar Rota',
    computing: 'Calculando rota…',
    route_found: 'Rota Encontrada',
    walking_directions: 'Instruções de Caminhada',
    path: 'Caminho',
    title_accessibility: 'Navegação de Acessibilidade',
    assistance_profile: 'Perfil de Assistência',
    select_all: 'Selecione tudo o que se aplica:',
    wheelchair: 'Usuário de cadeira de rodas',
    step_free: 'Rota sem degraus necessária',
    service_animal: 'Parada para animais de serviço',
    sensory: 'Rota amigável para os sentidos',
    amenities: 'Serviços Acessíveis Próximos',
    step_free_route: 'Rota Acessível Sem Degraus',
    distance: 'Distância',
    walk_time: 'Tempo de caminhada',
    title_transport: 'Transporte Sustentável',
    transport_subtitle: 'Encontre o caminho mais ecológico para o estádio.',
    select_transport: 'Selecionar Modo de Transporte',
    calc_carbon: 'Calcular Emissões de Carbono',
    travel_time: 'Tempo Estimado de Viagem',
    carbon_footprint: 'Pegada de Carbono',
    est_cost: 'Custo Estimado',
    sustainable_option: 'Opção Sustentável',
    simulate_ai: 'Simular IA Offline',
    offline: 'OFFLINE',
    footer_text: 'A IA nunca calcula rotas ou distâncias — apenas motor determinístico',
    meta_desc_wayfinding: 'FanFlow AI — Rotas rápidas e confiáveis no estádio para a Copa do Mundo da FIFA 2026. Obtenha direções determinísticas com contexto gerado por IA.',
    meta_desc_accessibility: 'FanFlow AI — Navegação acessível e sem degraus, perfis de assistência e busca de serviços acessíveis para os visitantes do estádio da Copa do Mundo.',
    meta_desc_transport: 'FanFlow AI — Compare emissões de carbono, custos e ETA para trânsito sustentável, carona compartilhada e estacionamento para chegar ao estádio.',
  },
  zh: {
    wayfinding: '寻路导航',
    accessibility: '无障碍服务',
    transport: '绿色交通',
    title_wayfinding: '寻路与路线规划',
    origin: '出发登机口',
    destination: '目的地区域',
    routing_mode: '路线模式',
    standard: '标准模式',
    accessible: '无障碍模式',
    accessible_route: '无障碍路线',
    congestion: '启用实时拥堵权重',
    find_route: '规划路线',
    computing: '正在计算路线…',
    route_found: '已找到路线',
    walking_directions: '步行指引',
    path: '路径',
    title_accessibility: '无障碍导航服务',
    assistance_profile: '无障碍协助档案',
    select_all: '请选择适用的项目：',
    wheelchair: '轮椅使用者',
    step_free: '需要无台阶通道',
    service_animal: '导盲犬休息区',
    sensory: '感官友好路线',
    amenities: '附近的无障碍设施',
    step_free_route: '无台阶无障碍路线',
    distance: '距离',
    walk_time: '步行时间',
    title_transport: '可持续绿色交通',
    transport_subtitle: '寻找前往体育场最环保的方式。',
    select_transport: '选择交通方式',
    calc_carbon: '计算碳排放',
    travel_time: '预计出行时间',
    carbon_footprint: '碳足迹',
    est_cost: '预计费用',
    sustainable_option: '环保出行方案',
    simulate_ai: '模拟人工智能离线',
    offline: '离线模式',
    footer_text: '人工智能绝不计算路线或距离 — 仅使用确定性计算引擎',
    meta_desc_wayfinding: 'FanFlow AI — 针对 2026 年国际足联世界杯场馆的快速且可靠的寻路导航服务。获取由人工智能生成上下文的确定性路线指引。',
    meta_desc_accessibility: 'FanFlow AI — 提供无障碍、无台阶导航、协助方案选择以及附近无障碍设施查询服务，为世界杯观众保驾护航。',
    meta_desc_transport: 'FanFlow AI — 比较前往体育场的绿色交通、网约车和自驾泊车的碳排放、费用及预计到达时间。',
  },
  de: {
    wayfinding: 'Wegfindung',
    accessibility: 'Barrierefreiheit',
    transport: 'Transport',
    title_wayfinding: 'Wegfindung & Routen',
    origin: 'Starttor',
    destination: 'Zielbereich',
    routing_mode: 'Routenmodus',
    standard: 'Standard',
    accessible: 'Barrierefrei',
    accessible_route: 'Barrierefreie Route',
    congestion: 'Live-Staugewichte verwenden',
    find_route: 'Route Finden',
    computing: 'Route wird berechnet…',
    route_found: 'Route Gefunden',
    walking_directions: 'Wegbeschreibung',
    path: 'Weg',
    title_accessibility: 'Barrierefreie Wegfindung',
    assistance_profile: 'Hilfebedarfsprofil',
    select_all: 'Bitte alles Zutreffende auswählen:',
    wheelchair: 'Rollstuhlfahrer',
    step_free: 'Stufenloser Weg erforderlich',
    service_animal: 'Begleithund-Entlastungsstelle',
    sensory: 'Sensibel gestaltete Route',
    amenities: 'Barrierefreie Einrichtungen in der Nähe',
    step_free_route: 'Stufenloser barrierefreier Weg',
    distance: 'Entfernung',
    walk_time: 'Gehzeit',
    title_transport: 'Nachhaltiger Transport',
    transport_subtitle: 'Finden Sie den umweltfreundlichsten Weg zum Stadion.',
    select_transport: 'Transportmittel Auswählen',
    calc_carbon: 'CO2-Emissionen Berechnen',
    travel_time: 'Geschätzte Reisezeit',
    carbon_footprint: 'CO2-Bilanz',
    est_cost: 'Geschätzte Kosten',
    sustainable_option: 'Nachhaltige Option',
    simulate_ai: 'KI-Offline-Modus simulieren',
    offline: 'OFFLINE',
    footer_text: 'KI berechnet niemals Routen oder Distanzen — nur deterministische Engine',
    meta_desc_wayfinding: 'FanFlow AI — Schnelle und zuverlässige Stadion-Wegfindung für die FIFA Fussball-Weltmeisterschaft 2026. Erhalten Sie deterministische Wegbeschreibungen mit KI-formuliertem Kontext.',
    meta_desc_accessibility: 'FanFlow AI — Barrierefreie, stufenlose Navigation, Hilfebedarfsprofile und barrierefreier Einrichtungsfinder für Stadionbesucher.',
    meta_desc_transport: 'FanFlow AI — Vergleichen Sie CO2-Emissionen, Kosten und ETAs für nachhaltige Verkehrsmittel, Fahrgemeinschaften und Parkplätze, um zum Stadion zu gelangen.',
  },
}

export function AIProvider({ children }: { children: ReactNode }) {
  const [aiOffline, setAiOffline] = useState(false)
  const [language, setLanguage] = useState('en')

  useEffect(() => {
    document.documentElement.lang = language
  }, [language])

  return (
    <AIContext.Provider value={{ aiOffline, setAiOffline, language, setLanguage }}>
      {children}
    </AIContext.Provider>
  )
}

export const useAI = () => useContext(AIContext)

export function useTranslation() {
  const { language } = useAI()
  return {
    t: (key: string): string => {
      return translations[language]?.[key] ?? translations['en']?.[key] ?? key
    }
  }
}
